export enum NotificationType{
    STAFF_RECRUITMENT, STAFF_RECRUITMENT_RESPONSE,ORGANIZER_INVITE,ORGANIZER_INVITE_RESPONSE,PARTICIPANT_INVITE,
    PARTICIPANT_INVITE_RESPONSE, STAFF_DEMAND_REQUEST,STAFF_DEMAND_RESPONSE,REMINDER,PUB_REACTION,PUB_TAG,PUB_COMMENTS
}
